
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { PiSunLight } from "react-icons/pi";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "My Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {


  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable}antialiased mx-5 mt-5`}
      >
        <header className="flex justify-between h-[5vh] ">
          <div>
            <ul className="flex gap-5">
              <li>
                <Link href={"/"}>Home</Link>
              </li>
              <li>
                <Link href={"/portfolio"}>Portfolio</Link>
              </li>
              <li>
                <Link href={"/testimonial"}>Testimonial</Link>
              </li>
              <li>
                <Link href={"/contact"}>Contact</Link>
              </li>
            </ul>
          </div>
          <div>
            <PiSunLight size={25} />
          </div>
        </header>
        {children}
      </body>
    </html>
  );
}
